# ========================== VARIABLES ==========================
x-client-args: &client-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: client
  DOCKER_NODE_VERSION: 20.11.1-slim
  DOCKER_UBUNTU_VERSION: jammy-20230624

x-math-args: &math-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: math
  DOCKER_NODE_VERSION: 20.11.1-slim

x-logger-args: &logger-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: logger
  DOCKER_NODE_VERSION: 20.11.1-slim

services:
# ========================== PRODUCTION ==========================
  client-prod:
    build:
      dockerfile: ./docker/Dockerfile-api
      target: production
      args: *client-args


# ========================== DEVELOPMENT ==========================
  client-dev:
    build:
      dockerfile: ./docker/Dockerfile-api
      target: development
      args: *client-args
    restart: unless-stopped
    volumes:
      - ./apps/client:/app/apps/client:ro
      - packages-math-ephemeral:/app/packages/math/dist:ro
      - packages-logger-ephemeral:/app/packages/logger/dist:ro
    depends_on:
      - math-dev
      - logger-dev

  math-dev:
    build:
      dockerfile: ./docker/Dockerfile-package
      target: builder
      args: *math-args
    restart: unless-stopped
    volumes:
      - ./packages/math/:/app/lib:ro
      - packages-math-ephemeral:/app/lib/dist:rw

  logger-dev:
    build:
      dockerfile: ./docker/Dockerfile-package
      target: builder
      args: *logger-args
    restart: unless-stopped
    volumes:
      - ./packages/logger/:/app/lib:ro
      - packages-logger-ephemeral:/app/lib/dist:rw

volumes:
  packages-math-ephemeral:
  packages-logger-ephemeral:
