# ========================== VARIABLES ==========================
x-api-args: &api-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: api
  DOCKER_NODE_VERSION: 20.11.1-slim
  DOCKER_UBUNTU_VERSION: jammy-20230624

x-logger-args: &logger-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: logger
  DOCKER_NODE_VERSION: 20.11.1-slim

services:
# ========================== PRODUCTION ==========================
  api-prod:
    build:
      dockerfile: ./docker/Dockerfile-node
      target: production
      args: *api-args


# ========================== DEVELOPMENT ==========================
  api-dev:
    build:
      dockerfile: ./docker/Dockerfile-node
      target: development
      args: *api-args
    restart: unless-stopped
    volumes:
      - ./apps/api:/workspace/apps/api:ro
      - packages-logger-ephemeral:/workspace/packages/logger/dist:ro
    depends_on:
      - logger-dev

  logger-dev:
    build:
      dockerfile: ./docker/Dockerfile-package
      target: builder
      args: *logger-args
    restart: unless-stopped
    volumes:
      - ./packages/logger/:/app/lib:ro
      - packages-logger-ephemeral:/app/lib/dist:rw

volumes:
  packages-logger-ephemeral:
