# ========================== VARIABLES ==========================
x-client-args: &client-args
  DOCKER_NODE_VERSION: 18.17.0-slim
  DOCKER_UBUNTU_VERSION: jammy-20230624

x-math-args: &math-args
  DOCKER_NODE_VERSION: 18.17.0-slim

x-logger-args: &logger-args
  DOCKER_NODE_VERSION: 18.17.0-slim

services:
# ========================== PRODUCTION ==========================
  client-prod:
    build:
      dockerfile: ./apps/client/Dockerfile
      target: production
      args: *client-args


# ========================== DEVELOPMENT ==========================
  client-dev:
    build:
      dockerfile: ./apps/client/Dockerfile
      target: development
      args: *client-args
    restart: unless-stopped
    volumes:
      - ./apps/client:/app/client:ro
      - packages-math-ephemeral:/app/packages/math/dist:ro
      - packages-logger-ephemeral:/app/packages/logger/dist:ro

  math-dev:
    build:
      dockerfile: ./packages/math/Dockerfile
      target: builder
      args: *math-args
    restart: unless-stopped
    volumes:
      - ./packages/math/:/app/lib:ro
      - packages-math-ephemeral:/app/lib/dist:rw

  logger-dev:
    build:
      dockerfile: ./packages/logger/Dockerfile
      target: builder
      args: *logger-args
    restart: unless-stopped
    volumes:
      - ./packages/logger/:/app/lib:ro
      - packages-logger-ephemeral:/app/lib/dist:rw

volumes:
  packages-math-ephemeral:
  packages-logger-ephemeral:
