# ========================== VARIABLES ==========================
x-api-args: &api-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: api
  DOCKER_NODE_VERSION: 20.11.1
  DOCKER_UBUNTU_VERSION: jammy-20230624

x-frontend-args: &frontend-args
  SCOPE: "@node-typescript-monorepo-template"
  PROJECT: frontend
  DOCKER_NODE_VERSION: 20.11.1
  DOCKER_UBUNTU_VERSION: jammy-20230624
  DOCKER_NGINX_VERSION: 1.26.0

services:
# ========================== PRODUCTION ==========================
  api-prod:
    build:
      dockerfile: ./docker/Dockerfile-node
      target: production
      args: *api-args
    env_file: .env

  frontend-prod:
    build:
      dockerfile: ./docker/Dockerfile-web
      target: production
      args: *frontend-args
    env_file: .env
    environment:
      PROXY_API: http://api-prod:${API_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}


# ========================== DEVELOPMENT ==========================
  api-dev:
    build:
      dockerfile: ./docker/Dockerfile-node
      target: development
      args: *api-args
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./apps/api:/workspace/apps/api:ro
      - ./packages:/workspace/packages:ro

  frontend-dev:
    build:
      dockerfile: ./docker/Dockerfile-web
      target: development
      args: *frontend-args
    restart: unless-stopped
    env_file: .env
    environment:
      PROXY_API: http://api-dev:${API_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ./apps/frontend:/workspace/apps/frontend
