# syntax=docker/dockerfile:1
ARG PROJECT

ARG USER=node
ARG WORKSPACE=/app

ARG DOCKER_NODE_VERSION=latest

# ========================== BUILDER STAGE ==========================
FROM node:${DOCKER_NODE_VERSION} AS builder
ARG PROJECT
ARG WORKSPACE

WORKDIR ${WORKSPACE}
COPY --chown=${USER}:${USER} ./packages/${PROJECT}/package.json ./
COPY --chown=${USER}:${USER} ./package-lock.json ./
RUN npm install

WORKDIR ${WORKSPACE}/lib
COPY --chown=${USER}:${USER} ./packages/${PROJECT} ./
RUN npm run build

CMD ["npm", "run", "build:watch"]
